alias ll='exa -lahF --time-style=long-iso --no-permissions --no-user --icons'
alias lr='ll -s=modified -r'
alias cat='bat --paging=never --decorations=never --color=always'
alias catd='bat --paging=never'
alias sudo='sudo '
# alias sudo='sudo -E '
